# Generated by Django 3.2.7 on 2023-08-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('i', 'Initiated'), ('p', 'In Progress'), ('c', 'Completed'), ('n', 'Not Completed')], default='i', max_length=1)),
                ('sub_status', models.CharField(choices=[('i', 'Initiated'), ('oc', 'Order Confirmed'), ('pf', 'Payment Failed'), ('ip', 'In Progress'), ('c', 'Completed'), ('n', 'Not Completed')], default='i', max_length=2)),
                ('payment_json', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status_timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.product')),
            ],
        ),
    ]
