# Generated by Django 3.2.7 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
