# Generated by Django 3.2.7 on 2023-08-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
