# Generated by Django 3.2.7 on 2023-08-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_order_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
