# Generated by Django 3.2.7 on 2023-08-16 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_product_is_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=None, max_length=255, null=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('i', 'Initiated'), ('p', 'In Progress'), ('c', 'Completed'), ('n', 'Not Completed')], default='i', max_length=1)),
                ('sub_status', models.CharField(choices=[('i', 'Initiated'), ('oc', 'Order Confirmed'), ('pf', 'Payment Failed'), ('ip', 'In Progress'), ('c', 'Completed'), ('n', 'Not Completed')], default='i', max_length=2)),
                ('order_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('payment_json', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('status_timeline', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
