# Generated by Django 3.2.7 on 2023-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_order_payment_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
