# Generated by Django 3.2.7 on 2023-09-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_order_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_reference_id',
        ),
        migrations.AddField(
            model_name='product',
            name='user_input_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='orders/qr_code/'),
        ),
    ]
